### ISSUE TITLE
Where to get PUB/PRIV keys using ESPHome Dashboard?

### ISSUE THREAD

**Issue by Araxion** [droscy/esp_wireguard#1]
Hi, i am trying to connect ESP32 running ESPHome BLE Proxy to my Wireguard VPN running on MikroTik, but i don`t know where to find keys for .yaml config. Can someone give me tip? Thanks!

**Comment by khenderick** [comment]
You can generate those keys on a computer with the wireguard tools installed. See https://www.wireguard.com/quickstart/#key-generation on how to generate those. Typically you'll need the server's _public key_ and the ESPHome device's _private key_ in the yaml.
